export const CURRENT_USER = {
    INIT: {
        IDLE: "CURRENT_USER_INIT_IDLE",
        SUCCESS: "CURRENT_USER_INIT_SUCCESS",
    },
    LOG_IN: {
        IDLE: "CURRENT_USER_LOG_IN_IDLE",
        SUCCESS: "CURRENT_USER_LOG_IN_IDLE",
    },
    AUTH: {
        IDLE: "CURRENT_USER_AUTH_IDLE",
        SUCCESS: "CURRENT_USER_AUTH_SUCCESS",
    }
};