export const PROBLEMS = {
    ADD: {
        IDLE: "PROBLEMS_ADD_IDLE",
        SUCCESS: "PROBLEMS_ADD_SUCCESS",
        FAILURE: "PROBLEMS_ADD_FAILURE",
    },
    INIT: {
        IDLE: "PROBLEMS_INIT_IDLE",
        SUCCESS: "PROBLEMS_INIT_SUCCESS",
        FAILURE: "PROBLEMS_INIT_FAILURE",
    },
    UPDATE: {
        IDLE: "PROBLEMS_UPDATE_IDLE",
        SUCCESS: "PROBLEMS_UPDATE_SUCCESS",
        FAILURE: "PROBLEMS_UPDATE_FAILURE",
    },
};
