export const EVENTS = {
    INIT: {
        IDLE: "EVENTS_INIT_IDLE",
        SUCCESS: "EVENTS_INIT_SUCCESS",
        FAILURE: "EVENTS_INIT_FAILURE",
    },
    ADD: {
        IDLE: "EVENTS_ADD_IDLE",
        SUCCESS: "EVENTS_ADD_SUCCESS",
        FAILURE: "EVENTS_ADD_FAILURE",
    },
    DELETE: {
        IDLE: "EVENTS_DELETE_IDLE",
        SUCCESS: "EVENTS_DELETE_SUCCESS",
        FAILURE: "EVENTS_DELETE_FAILURE",
    },
    EDIT: {
        IDLE: "EVENTS_EDIT_IDLE",
        SUCCESS: "EVENTS_EDIT_SUCCESS",
        FAILURE: "EVENTS_EDIT_FAILURE",
    },
};
